FROM node:20.5.0-alpine3.18

WORKDIR /usr/src/apps
COPY apps/server .


RUN npm install -g pnpm \
&& pnpm install \
&& pnpm run build 


ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

ENTRYPOINT ["node", "dist/worker.js"]