name: Publish Sacflow
on:
  push:
    branches:
      - main
    paths:
      - "apps/server/**"
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: "apps/server"
          sparse-checkout-cone-mode: false

      - name: setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.3

      - name: cache PNPM
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            apps/server/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('apps/server/package.json') }}
          restore-keys: |
            ${{ runner.os }}-pnpm

      - name: install dependencies
        run: |
          cd apps/server && pnpm install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: |
          cd apps/server && \
          docker image build -t sacflow:1.0 . 
      - name: test image to create
        run: | 
         docker image ls

